version: "1"
networks:
  services:
    external: true

services:
  auth:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/.venv
    networks:
      - services
    expose:
      - 8000
    command: >
      sh -c "
      python main.py
      "
