version: "3.8"  

services:
  auth:
    build:
      context: .
      dockerfile: Dockerfile  
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - /app/.venv
    networks:
      - services
    expose:
      - 8000
    command: uvicorn main:app --host 0.0.0.0 --port 8000  

  authdb:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - services

networks:
  services:
    external: true

volumes:
  postgres_data:
